#!/bin/sh

MODULE_NAME=atmel_ptc

if [ $(find /lib/modules/$(uname -r) -name $MODULE_NAME.ko | wc -l) == 0 ]
then
	echo "$MODULE_NAME module not found!"
	exit 1
fi

lsmod | grep $MODULE_NAME &> /dev/null
if [ $? == 0 ]
then
	echo "remove $MODULE_NAME driver..."
	modprobe -r $MODULE_NAME
fi

echo "load $MODULE_NAME module with ptc_cfg_qt1_self configuration..."
modprobe $MODULE_NAME configuration_file=microchip/ptc_cfg_qt1_self.bin
echo "start ptc_qt1_self_demo..."
ptc_qt1_self_demo
